version: "3"

services:
    mysql:
        image: mysql:5.6
        environment:
            MYSQL_DATABASE: bizschema
            MYSQL_ROOT_PASSWORD: rootpw
            MYSQL_USER: devroot
            MYSQL_PASSWORD: devpw
        volumes:
            - local-mysqlvol:/var/lib/mysql
        ports:
            - 3306:3306
        container_name: local-mysql

volumes:
    local-mysqlvol: