version: "3"

services:
    mysql:
        image: mysql:5.6
        environment:
            MYSQL_DATABASE: bizschema
            MYSQL_ROOT_PASSWORD: rootpw
            MYSQL_USER: devroot
            MYSQL_PASSWORD: devpw
            LANG: C.UTF-8
        volumes:
            - local-mysqlvol:/var/lib/mysql
        ports:
            - 3306:3306
        command:  --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci
        container_name: local-mysql
    
    redis:
        image: redis:alpine
        hostname: redis-local
        ports:
            - 6379:6379
        container_name: local-redis
        

volumes:
    local-mysqlvol: